print('Dê o resultado para cada um dos seguintes:')
print('a) 22 * 3 | R: ', 22 * 3)
print('b) 15 % 4 | R: ', 15 % 4)
print('c) 3 ** 2 | R: ', 3 ** 2)
print('\n')

print('Dê o resultado exato de cada uma das divisões seguintes:')
print('a) 5 / 4 | R: ', 5 / 4)
print('b) 5 // 4 | R: ', 5 // 4)
print('c) 5.0 // 4 | R: ', 5.0 // 4)
print('\n')

print('Quantos operandos existem na expressão aritmética seguinte? 2 * 24 + 60 - 10')
print('a) 4')
print('b) 3')
print('c) 7')
print('Resposta correta: b) 3')
print('\n')

print('Quantos operadores binários existem na expressão aritmética seguinte? - 10 + 25 / (16 + 12)')
print('a) 2')
print('b) 3')
print('c) 4')
print('Resposta correta: b) 3')
